version: 2

x_dim_station_columns:
  &dim_station_columns
  columns:
    - name: station_pk
      description: "Station's surrogate key"
      tests:
        - not_null
        - unique
    - name: id
      description: "Natural key of station"
      tests:
        - not_null
        - unique
    - name: name
      description: "Name of station"
      tests:
        - not_null

x_dim_time_of_day_columns:
  &dim_time_of_day_columns
  columns:
    - name: time_of_day_hour
      description: "The hour of the day, represented as an integer from 0 to 23"
      tests:
        - not_null
        - unique
        - accepted_values:
            values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
    - name: time_of_day_label
      description: "Time of day label (Morning, Afternoon, Evening, Night)"
      tests:
        - not_null
        - accepted_values:
            values: ["Night", "Morning", "Afternoon", "Evening"]

x_dim_date_columns:
  &dim_date_columns
  columns:
    - name: id
      description: "Unique identifier for each day, generated as YYYYMMDD (eg. 20240124)"
      tests:
        - not_null
        - unique
    - name: date_day
      description: "The date itself"
      tests:
        - not_null
        - unique
    - name: year
      description: "The year part of the date"
      tests:
        - not_null
    - name: month
      description: "The month part of the date"
      tests:
        - not_null
    - name: day
      description: "The day part of the date"
      tests:
        - not_null
    - name: quarter
      description: "The quarter of the year (1 to 4)"
      tests:
        - not_null
        - accepted_values:
            values: [ 1, 2, 3, 4 ]
    - name: weekday_iso
      description: "The ISO day of the week (1 = Monday, 7 = Sunday)"
      tests:
        - not_null
        - accepted_values:
            values: [ 1, 2, 3, 4, 5, 6, 7 ]
    - name: weekday_name
      description: "The name of the day"
      tests:
        - not_null
        - accepted_values:
            values: [ "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" ]
    - name: month_name
      description: "The name of the month"
      tests:
        - not_null
        - accepted_values:
            values: [ "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" ]
    - name: weekday_indicator
      description: "Indicates if the date is a Weekday or Weekend"
      tests:
        - not_null
        - accepted_values:
            values: [ "Weekday", "Weekend" ]
    - name: week_of_year
      description: "The ISO week number of the year"
      tests:
        - not_null

models:
  - name: fct_rides
    description: "Summary of rides"
    columns:
      - name: ride_id
        description: "Unique identifier for each ride"
        tests:
          - not_null
          - unique
      - name: rideable_type_fk
        description: "Foreign key to the rideable type dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_rideable_type')
              field: id
      - name: started_at_date_fk
        description: "Foreign key to the date dimension representing the start date of the ride"
        tests:
          - not_null
          - relationships:
              to: ref('dim_started_at_date')
              field: id
      - name: ended_at_date_fk
        description: "Foreign key to the date dimension representing the end date of the ride"
        tests:
          - not_null
          - relationships:
              to: ref('dim_ended_at_date')
              field: id
      - name: started_at_time_of_day_fk
        description: "Foreign key to the time of day dimension representing start time of ride"
        tests:
          - not_null
          - relationships:
              to: ref('dim_time_of_day')
              field: time_of_day_hour
      - name: ended_at_time_of_day_fk
        description: "Foreign key to the time of day dimension representing end time of ride"
        tests:
          - not_null
          - relationships:
              to: ref('dim_time_of_day')
              field: time_of_day_hour
      - name: start_station_fk
        description: "Foreign key to the stations dimension representing starting station"
        tests:
          - not_null
          - relationships:
              to: ref('dim_start_station')
              field: station_pk
      - name: end_station_fk
        description: "Foreign key to the stations dimension representing end station"
        tests:
          - not_null
          - relationships:
              to: ref('dim_end_station')
              field: station_pk
      - name: start_lat
        description: "Latitude of starting location"
        tests:
          - not_null
      - name: start_lng
        description: "Longitude of starting location"
        tests:
          - not_null
      - name: end_lat
        description: "Latitude of starting location"
      - name: end_lng
        description: "Longitude of starting location"
      - name: rent_type_fk
        description: "Foreign key to the rent type dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_rent_type')
              field: id
  - name: dim_station
    description: "Base stations dimension table"
    <<: *dim_station_columns

  - name: dim_start_station
    description: "Start stations dimension table"
    <<: *dim_station_columns

  - name: dim_end_station
    description: "End stations dimension table"
    <<: *dim_station_columns

  - name: dim_rideable_type
    description: "Rideable types dimension table"
    columns:
      - name: id
        description: "Unique identifier"
        tests:
          - not_null
          - unique
      - name: name
        description: "Name of the rideable type"
        tests:
          - not_null
  - name: dim_rent_type
    description: "Type of rent"
    columns:
      - name: id
        description: "Unique identifier"
        tests:
          - not_null
          - unique
      - name: name
        description: "Name of the rent type"
        tests:
          - not_null
          - accepted_values:
              values: ['member', 'casual', 'day_pass']
  - name: dim_time_of_day
    description: "Dimension table that categorizes hour into different time of day periods"
    <<: *dim_time_of_day_columns
  - name: dim_started_at_time_of_day
    description: "Dimension table that categorizes hour into different time of day periods"
    <<: *dim_time_of_day_columns
  - name: dim_ended_at_time_of_day
    description: "Dimension table that categorizes hour into different time of day periods"
    <<: *dim_time_of_day_columns
  - name: dim_date
    description: "Base date dimension for time-based analysis"
    <<: *dim_date_columns
  - name: dim_started_at_date
    description: "Start date dimension"
    <<: *dim_date_columns
  - name: dim_ended_at_date
    description: "End date dimension"
    <<: *dim_date_columns
